from django.urls import path

from .views import (
    BookingDetailView,
    BookingListCreateView,
    BusinessOfferDetailView,
    BusinessOfferListCreateView,
    BusinessTableDetailView,
    BusinessTableListCreateView,
    CategoryListCreateView,
    ManagerDetailView,
    ManagerListCreateView,
    PartnerProfileView,
    ProfileImageView,
    ServiceDetailView,
    ServiceImageUploadView,
    ServiceImageView,
    ServiceKindListCreateView,
    ServiceListCreateView,
    SpecialistDetailView,
    SpecialistListCreateView,
)

urlpatterns = [
    path("profile/", PartnerProfileView.as_view(), name="partner-profile"),
    path("business-tables/", BusinessTableListCreateView.as_view(), name="partner-business-tables"),
    path("business-tables/<int:table_id>/", BusinessTableDetailView.as_view(), name="partner-business-table-detail"),
    path("business-offers/", BusinessOfferListCreateView.as_view(), name="partner-business-offers"),
    path("business-offers/<int:offer_id>/", BusinessOfferDetailView.as_view(), name="partner-business-offer-detail"),
    path("categories/", CategoryListCreateView.as_view(), name="partner-categories"),
    path("service-kinds/", ServiceKindListCreateView.as_view(), name="partner-service-kinds"),
    path("services/", ServiceListCreateView.as_view(), name="partner-services"),
    path("services/<int:service_id>/", ServiceDetailView.as_view(), name="partner-service-detail"),
    path("services/upload-image/", ServiceImageUploadView.as_view(), name="partner-service-image-upload"),
    path("service-images/<str:file_name>/", ServiceImageView.as_view(), name="partner-service-image"),
    path("profile-images/<str:file_name>/", ProfileImageView.as_view(), name="partner-profile-image"),
    path("managers/", ManagerListCreateView.as_view(), name="partner-managers"),
    path("managers/<int:manager_id>/", ManagerDetailView.as_view(), name="partner-manager-detail"),
    path("specialists/", SpecialistListCreateView.as_view(), name="partner-specialists"),
    path("specialists/<int:specialist_id>/", SpecialistDetailView.as_view(), name="partner-specialist-detail"),
    path("bookings/", BookingListCreateView.as_view(), name="partner-bookings"),
    path("bookings/<int:booking_id>/", BookingDetailView.as_view(), name="partner-booking-detail"),
]
