# Generated by Django 5.0.7 on 2026-06-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_api', '0012_service_image_base64'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerServiceKind',
        ),
    ]
