# Generated by Django 5.0.7 on 2026-10-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_api', '0024_booking_pricing_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('manual', 'Manual'), ('mobile', 'Mobile')], default='unknown', max_length=20),
        ),
    ]
