# Generated by Django 5.0.7 on 2026-05-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
